// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgtnwkksrupynwdtbrge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndG53a2tzcnVweW53ZHRicmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyODIwNjcsImV4cCI6MjA4ODg1ODA2N30.-eCLQnUtNTAJa__16wqovCgORfm6ozbw7uReffHlgEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});